services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server/:/financial/server
      - ./.env/:/financial/.env
      - ./src/:/financial/src
      - ./package.json:/financial/package.json
      - ./yarn.lock:/financial/yarn.lock
      - ./nodemon.json:/financial/nodemon.json
      - ./tsconfig.server.json:/financial/tsconfig.server.json
  src:
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - ./src/:/financial/src
      - ./package.json:/financial/package.json
      - ./yarn.lock:/financial/yarn.lock
    ports:
      - "3000:3000"
