// @flow

export const Actions = {
    UPDATE_STATE: 'UPDATE_STATE',
    SET_USERS: 'SET_USERS',
    SET_SCREEN: 'SET_SCREEN',
    UPDATE_PREFERENCES: 'UPDATE_PREFERENCES',
    REFRESH_WIDGETS: 'REFRESH_WIDGETS',
    SET_BASE_CURRENCY_ID: 'SET_BASE_CURRENCY_ID',
    UPDATE_CURRENCIES: 'UPDATE_CURRENCIES',
    SHOW_SNACKBAR: 'SHOW_SNACKBAR',
    HIDE_SNACKBAR: 'HIDE_SNACKBAR',
};
