export enum Action {
    UPDATE_STATE= 'UPDATE_STATE',
    SET_USERS= 'SET_USERS',
    SET_SCREEN= 'SET_SCREEN',
    UPDATE_PREFERENCES= 'UPDATE_PREFERENCES',
    REFRESH_WIDGETS= 'REFRESH_WIDGETS',

    SHOW_SNACKBAR= 'SHOW_SNACKBAR',
    HIDE_SNACKBAR= 'HIDE_SNACKBAR',
};
