export const Actions = {
    $INIT: '@@INIT',
    UPDATE_STATE: 'UPDATE_STATE',
    LOADING_ENABLE: 'LOADING_ENABLE',
    LOADING_DISABLE: 'LOADING_DISABLE',
    UPDATE_USER: 'UPDATE_USER',
    SET_SCREEN: 'SET_SCREEN',
    UPDATE_PREFERENCES: 'UPDATE_PREFERENCES',
    REFRESH_WIDGETS: 'REFRESH_WIDGETS',
};
